
package planillas_drec;


import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author aE
 * 
 *                  Julio 07 de 2021 -
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    frm_planilla_v2 frm_planilla_v2;
    frm_consulta frm_consulta;
    frm_usuario frm_usuario;
    frm_pagos frm_pagos;
    frm_back_up back;
    public frm_menu() throws SQLException {
        initComponents();
        String a = frm_Login.user;
        redirigir_form(a);
        setLocationRelativeTo(null);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cap.png"));
        return retValue;
    }
    
    cConexion c = new cConexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_planilla = new javax.swing.JMenu();
        jMenu2_reporte = new javax.swing.JMenu();
        jMenu3_pagos = new javax.swing.JMenu();
        jMenu4_usuario = new javax.swing.JMenu();
        jMenu5_backup = new javax.swing.JMenu();
        jMenu6_salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/drec.jpg"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1_planilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libro1.png"))); // NOI18N
        jMenu1_planilla.setText("<html><font size=+1>PLANILLA</font>");
        jMenu1_planilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1_planillaMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1_planilla);

        jMenu2_reporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consultar.png"))); // NOI18N
        jMenu2_reporte.setText("<html><font size=+1>BOLETAS</font>");
        jMenu2_reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2_reporteMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2_reporte);

        jMenu3_pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagos_icon.png"))); // NOI18N
        jMenu3_pagos.setText("<html><font size=+1>PAGOS</font>");
        jMenu3_pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3_pagosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3_pagos);

        jMenu4_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N
        jMenu4_usuario.setText("<html><font size=+1>USUARIOS</font>");
        jMenu4_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4_usuarioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4_usuario);

        jMenu5_backup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backup.png"))); // NOI18N
        jMenu5_backup.setText("<html><font size=+1>BACKUP</font>");
        jMenu5_backup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5_backupMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5_backup);

        jMenu6_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jMenu6_salir.setText("salir");
        jMenu6_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6_salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6_salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1_planillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1_planillaMouseClicked
        frm_planilla_v2 = new frm_planilla_v2();
        frm_planilla_v2.setVisible(true);       
        this.dispose();
    }//GEN-LAST:event_jMenu1_planillaMouseClicked

    private void jMenu6_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6_salirMouseClicked
        c.desconectar();
        System.exit(0);
    }//GEN-LAST:event_jMenu6_salirMouseClicked

    private void jMenu2_reporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2_reporteMouseClicked
        try {
            frm_consulta = new frm_consulta();
            frm_consulta.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
        }       
    }//GEN-LAST:event_jMenu2_reporteMouseClicked

    private void jMenu4_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4_usuarioMouseClicked
        frm_usuario = new frm_usuario();
        frm_usuario.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu4_usuarioMouseClicked

    private void jMenu3_pagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3_pagosMouseClicked
//        try {
//            frm_pagos = new frm_pagos();
//            frm_pagos.setVisible(true);
//            this.dispose();
//        } catch (SQLException ex) {
//            Logger.getLogger(frm_menu.class.getName()).log(Level.SEVERE, null, ex);
//        }   
    }//GEN-LAST:event_jMenu3_pagosMouseClicked
    int xx,yy;
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jMenu5_backupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5_backupMouseClicked
        back = new frm_back_up();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu5_backupMouseClicked
    public void ran(){
        int n =(int) (Math.random()*11);//random 0-10
        // uf se soluciono lo del jar 04.08.2021 yeahhhhh :)
        // por que estaré riendo, luego estaré sufriendo, rayos, ni modo. that's life! Js
        if(n==1 || n==9){
            ImageIcon img = new ImageIcon(getClass().getResource("/imagenes/drec-cusco.jpg"));
            Icon icono = new ImageIcon(img.getImage().getScaledInstance(jLabel1.getWidth(),jLabel1.getHeight(),Image.SCALE_REPLICATE));
            jLabel1.setIcon(icono); 
        }
    }
    public void redirigir_form(String user) throws SQLException{
        String privilegio = c.tipo_user(user);
        //System.out.println("pri: "+privilegio);
        if(privilegio.equals("planillero")){
            jMenu4_usuario.setVisible(false);
            jMenu5_backup.setVisible(false);
            ran();
        }
        else if(privilegio.equals("consultor")){
            jMenu1_planilla.setVisible(false);
            jMenu4_usuario.setVisible(false);
            jMenu5_backup.setVisible(false);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1_planilla;
    private javax.swing.JMenu jMenu2_reporte;
    private javax.swing.JMenu jMenu3_pagos;
    private javax.swing.JMenu jMenu4_usuario;
    private javax.swing.JMenu jMenu5_backup;
    private javax.swing.JMenu jMenu6_salir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
