/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package planillas_drec;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author aE
 */
public class frm_Login extends javax.swing.JFrame {

    
    frm_menu frm_menu;
   
    public frm_Login() {
        initComponents();
        TextPrompt u = new TextPrompt("usuario",txt_user);
        TextPrompt p = new TextPrompt("contraseña",txt_password);
        setLocationRelativeTo(null);
    }
    cConexion c = new cConexion();
    public static String user = "";
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cap.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_logo_drec = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_icon_drec = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        btn_iniciar = new javax.swing.JButton();
        icon_lock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        icon_lock1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo_drec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_drec_opt.png"))); // NOI18N
        getContentPane().add(lbl_logo_drec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 300, 410));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("© GEREDU/CENTRO CÓMPUTO 2021");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 180, -1));

        lbl_icon_drec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wall.jpg"))); // NOI18N
        lbl_icon_drec.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbl_icon_drecMouseDragged(evt);
            }
        });
        lbl_icon_drec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_icon_drecMousePressed(evt);
            }
        });
        getContentPane().add(lbl_icon_drec, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_titulo.setText("Inicio de sesión");
        jPanel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));

        txt_user.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt_user.setBorder(null);
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 240, 30));

        btn_iniciar.setBackground(new java.awt.Color(153, 153, 153));
        btn_iniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_iniciar.setText("INICIAR");
        btn_iniciar.setBorder(null);
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        btn_iniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_iniciarKeyPressed(evt);
            }
        });
        jPanel1.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 190, 40));

        icon_lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_opt.png"))); // NOI18N
        jPanel1.add(icon_lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 64, 60));

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("___________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, -1));

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("___________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 310, 20));

        icon_lock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lock_red.png"))); // NOI18N
        jPanel1.add(icon_lock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 64, 60));

        txt_password.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        txt_password.setBorder(null);
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 240, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 350, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        String u = txt_user.getText().trim();
        String p = txt_password.getText().trim();
        try {
            acceder(u,p);
        } catch (SQLException ex) {
            Logger.getLogger(frm_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        c.desconectar();
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
            btn_iniciar.doClick();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void btn_iniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_iniciarKeyPressed
        if(evt.getExtendedKeyCode() == KeyEvent.VK_ENTER){
            btn_iniciar.doClick();
        }
    }//GEN-LAST:event_btn_iniciarKeyPressed
    int xx,yy;
    private void lbl_icon_drecMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_icon_drecMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_lbl_icon_drecMousePressed

    private void lbl_icon_drecMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_icon_drecMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_lbl_icon_drecMouseDragged
    
    public void acceder(String us, String pass) throws SQLException
    {
        try {
            c.conexion();//conecta a la bd
            int n = c.buscar(us);
            if(n!=0)
            {
                boolean flag_user = c.get_user_pass(us, pass);
                if(flag_user){
                    user = us;
                    mostrar_menu();
                }
                else
                    JOptionPane.showMessageDialog(null, "Has introducido un usuario o contraseña incorrecta.\n Vuelva a intentarlo. ", "MENSAJE", JOptionPane.WARNING_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null, "Has introducido un usuario o contraseña de forma incorrecta.\n Vuelva a intentarlo. ", "MENSAJE", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+e);
        }
    }
    public void mostrar_menu() throws SQLException{
        frm_menu = new frm_menu();
        frm_menu.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel icon_lock;
    private javax.swing.JLabel icon_lock1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_icon_drec;
    private javax.swing.JLabel lbl_logo_drec;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
