/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package planillas_drec;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.FontFactory;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
/**
 *
 * @author aE
 */
public class frm_consulta extends javax.swing.JFrame {

    /**
     * Creates new form frm_consulta
     */
    frm_menu menu;
    frm_pagos pagos;
    frm_planilla_v2 planilla;
    frm_consolidado consolidado;
    public frm_consulta() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        frm_Login us = new frm_Login();
        String a = us.user;
        redirigir_form(a);
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cap.png"));
        return retValue;
    }
    cConexion c = new cConexion();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_inicio_ = new javax.swing.JButton();
        btn_planilla = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_consolidado = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        combo_mes = new javax.swing.JComboBox();
        btn_GENERAR_REPORTE_ = new javax.swing.JButton();
        rbtn_txt = new javax.swing.JRadioButton();
        rbtn_pdf = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ap_paterno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_ap_materno = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_nombres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("MES :");

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btn_inicio_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house.png"))); // NOI18N
        btn_inicio_.setText("INICIO                ");
        btn_inicio_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicio_ActionPerformed(evt);
            }
        });

        btn_planilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/book.png"))); // NOI18N
        btn_planilla.setText("PLANILLA          ");
        btn_planilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_planillaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GERENCIA REGIONAL");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DE EDUCACIÓN CUSCO");

        btn_consolidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consolidado.png"))); // NOI18N
        btn_consolidado.setText("CONSOLIDADO");
        btn_consolidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consolidadoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel9.setText("© GEREDU/CENTRO CÓMPUTO 2021");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_inicio_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_planilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_consolidado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_inicio_, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_planilla, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_consolidado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        txt_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_yearKeyTyped(evt);
            }
        });

        combo_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        btn_GENERAR_REPORTE_.setBackground(new java.awt.Color(255, 102, 0));
        btn_GENERAR_REPORTE_.setText("GENERAR");
        btn_GENERAR_REPORTE_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GENERAR_REPORTE_ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtn_txt);
        rbtn_txt.setText("txt");

        buttonGroup1.add(rbtn_pdf);
        rbtn_pdf.setText("pdf");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CONSULTAR BOLETA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("_");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("AÑO  :");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("AP. PATERNO   :");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("AP. MATERNO  :");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel12.setText("NOMBRES         :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_ap_materno)
                                                .addComponent(txt_ap_paterno)
                                                .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_GENERAR_REPORTE_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rbtn_txt)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_pdf, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_ap_paterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_ap_materno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_pdf)
                    .addComponent(rbtn_txt))
                .addGap(18, 18, 18)
                .addComponent(btn_GENERAR_REPORTE_)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void redirigir_form(String user) throws SQLException{
        String privilegio = c.tipo_user(user);
        if(privilegio.equals("planillero")){
            btn_consolidado.setVisible(false);
        }
        else if(privilegio.equals("consultor")){
            btn_planilla.setVisible(false);
            btn_consolidado.setVisible(false);
        }
    }    
    public String[] len(String a[]){
        for (int i = 0; i < a.length; i++) {
            a[i] = String.format("%-25s", a[i]);
        }
        return a;       
    }
    public void eliminar_null(ArrayList nombre_campos_hab_des, ArrayList valor_hab_des,
            ArrayList campos_aux, ArrayList valor_aux,int p_ini, int p_fin){
        int k=0;
        for (int i = p_ini; i < p_fin; i++) {
            if(valor_hab_des.get(i)!=(null)){
                campos_aux.add(nombre_campos_hab_des.get(k));
                valor_aux.add(valor_hab_des.get(i));                
            }
            k++;       
        } 
    }
    public void alinear_h_d(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%-15s", a.get(i)));
        }   
    }
    public void alinear_h_d_valores(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%8s", a.get(i)));
        }   
    }
    public void alinear_campos_importes(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%-10s", a.get(i)));//se le puede pasar como parametro el nro, ojo
        }   
    }
    public void alinear_valores_importes(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%10s", a.get(i)));
        }   
    }
    /*public void generar_boleta_txt(String []campos_boleta, ArrayList campos_importes, ArrayList campos_haberes, ArrayList campos_descuentos, 
            ArrayList<String> boleta,ArrayList<String> importes,ArrayList<String> haberes,ArrayList<String> descuentos){
        try {
            /////while para hacerlo por si existen ,as de 1 persona mismo nombre y fecha
            //while(){}
            String entorno = System.getenv("USERNAME");
            LocalDateTime d = LocalDateTime.now();
            String date = d.toString();
            String r = "";
            String [] xd = date.split(":");
            for (int i = 0; i < xd.length -1; i++) {
                r=r+xd[i]+"_";
            } 
            FileWriter fw1 = new FileWriter("C:\\Users\\"+entorno+"\\Documents\\"+r+"Archivo.txt");
            BufferedWriter bw1 = new BufferedWriter(fw1);
            ArrayList<String> aux_campos_h_d = new ArrayList();
            ArrayList<String> aux_valores_h_d = new ArrayList();
            int n=0;
            int ini_h=0, fin_h=50;
            int ini_d=0, fin_d=77;
            bw1.newLine();
            bw1.write("GEREDU CUSCO");
            bw1.newLine();
            bw1.newLine();
            for (int i = 0; i < 13; i++) {
                bw1.write(campos_boleta[i]+": "+boleta.get(n));
                bw1.newLine();
                n++;
            }
            bw1.write("======================================================================");//70
            bw1.newLine();
            eliminar_null(campos_haberes,haberes,aux_campos_h_d,aux_valores_h_d,ini_h,fin_h);
            alinear_h_d(aux_campos_h_d);
            alinear_h_d_valores(aux_valores_h_d);
            for (int i = 0; i < aux_campos_h_d.size(); i++) {
                bw1.write("+"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                bw1.newLine();                  
            }
            aux_campos_h_d.clear();
            aux_valores_h_d.clear();
            eliminar_null(campos_descuentos,descuentos,aux_campos_h_d,aux_valores_h_d,ini_d,fin_d);
            alinear_h_d(aux_campos_h_d);
            alinear_h_d_valores(aux_valores_h_d);
            for (int i = 0; i < aux_campos_h_d.size(); i++) {
                bw1.write("-"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                bw1.newLine();                  
            }
            aux_campos_h_d.clear();
            aux_valores_h_d.clear();
            bw1.write("======================================================================");
            bw1.newLine();
            alinear_campos_importes(campos_importes);
            alinear_valores_importes(importes);
            bw1.write(campos_importes.get(0)+"  "+importes.get(0)+"  "+campos_importes.get(1)+"  "+importes.get(1)+"  "+campos_importes.get(2)+"  "+importes.get(2));
            bw1.close();
            fw1.close();
            JOptionPane.showMessageDialog(null, "Se generó correctamente su txt.\nUbicación: Documentos");
        } catch (IOException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error, no se pudo generar su txt: \n"+e);
        }         
    }
    */
    ////////txt con mas de 1 persona mismo nombre y fecha
      public void generar_boleta_txt(String []campos_boleta, ArrayList campos_importes, ArrayList campos_haberes, ArrayList campos_descuentos, 
            ArrayList<String> boleta,ArrayList<String> importes,ArrayList<String> haberes,ArrayList<String> descuentos){
       try {
            String entorno = System.getenv("USERNAME");
            LocalDateTime d = LocalDateTime.now();
            String date = d.toString();
            String r = "";
            String [] xd = date.split(":");
            for (int i = 0; i < xd.length -1; i++) {
                r=r+xd[i]+"_";
            }
            FileWriter fw1 = new FileWriter("C:\\Users\\"+entorno+"\\Documents\\"+r+"Archivo.txt");
            BufferedWriter bw1 = new BufferedWriter(fw1);
            ArrayList<String> aux_campos_h_d = new ArrayList();
            ArrayList<String> aux_valores_h_d = new ArrayList();
            int n=0;
            int ini_h=0, fin_h=50;
            int ini_d=0, fin_d=77;
            int longitud = boleta.size()/13;
            int p = 0;
            String formatString = String.format("%%0%dd", 5);
            for (int j = 0; j < longitud; j++) {
                bw1.newLine();
                bw1.write("GEREDU CUSCO");
                bw1.newLine();
                bw1.newLine();
                for (int i = 0; i < 13; i++) {
                    bw1.write(campos_boleta[i]+": "+boleta.get(n));
                    bw1.newLine();
                    n++;
                }
                bw1.write("======================================================================");
                bw1.newLine();
                eliminar_null(campos_haberes,haberes,aux_campos_h_d,aux_valores_h_d,ini_h,fin_h);
                alinear_h_d(aux_campos_h_d);
                alinear_h_d_valores(aux_valores_h_d);
                for (int i = 0; i < aux_campos_h_d.size(); i++) {
                    bw1.write("+"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                    bw1.newLine();                  
                }
                aux_campos_h_d.clear();
                aux_valores_h_d.clear();
                eliminar_null(campos_descuentos,descuentos,aux_campos_h_d,aux_valores_h_d,ini_d,fin_d);
                alinear_h_d(aux_campos_h_d);
                alinear_h_d_valores(aux_valores_h_d);
                for (int i = 0; i < aux_campos_h_d.size(); i++) {
                    bw1.write("-"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                    bw1.newLine();                  
                }
                aux_campos_h_d.clear();
                aux_valores_h_d.clear();
                bw1.write("======================================================================");
                bw1.newLine();
                alinear_campos_importes(campos_importes);
                alinear_valores_importes(importes);
                bw1.write(campos_importes.get(0)+"  "+importes.get(p)+"  "+campos_importes.get(1)+"  "+importes.get(p+1)+"  "+campos_importes.get(2)+"  "+importes.get(p+2));
                bw1.newLine();
                bw1.newLine();
                bw1.newLine();
                String formattedString = String.format(formatString, j+1);
                bw1.write("                                                                 "+formattedString);
                bw1.newLine();
                bw1.write("....................................OTRO...............................");
                bw1.newLine();
                bw1.newLine();
                ini_h+=50;
                fin_h+=50;
                ini_d+=77;
                fin_d+=77;
                p+=3;
            } 
            bw1.close();
            fw1.close();
            JOptionPane.showMessageDialog(null, "Se generó correctamente su txt.\nUbicación: Documentos");
        } catch (IOException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error, no se pudo generar su txt: \n"+e);
        }        
    }
    //////////////
    ////////PDF para persona con mismo nombre y fecha////
       public void generar_boleta_pdf(String []campos_boleta, ArrayList campos_importes, ArrayList campos_haberes, ArrayList campos_descuentos, 
            ArrayList<String> boleta,ArrayList<String> importes,ArrayList<String> haberes,ArrayList<String> descuentos){
        try {                      
            String entorno = System.getenv("USERNAME");
            LocalDateTime d = LocalDateTime.now();
            String date = d.toString();
            String r = "";
            String [] xd = date.split(":");
            for (int i = 0; i < xd.length -1; i++) {
                r=r+xd[i]+"_";
            }
            String ruta = "C:\\Users\\"+entorno+"\\Documents\\"+r+"Archivo.pdf";
            Document doc = new Document();
            PdfWriter.getInstance(doc,new FileOutputStream(ruta));            
            doc.open();
            Paragraph parrafo = new Paragraph();
            parrafo.setFont(FontFactory.getFont("COURIER", 12));
            ArrayList<String> aux_campos_h_d = new ArrayList();
            ArrayList<String> aux_valores_h_d = new ArrayList();
            int n=0;
            int ini_h=0, fin_h=50;
            int ini_d=0, fin_d=77; 
            int longitud = boleta.size()/13;
            int p = 0;
            String formatString = String.format("%%0%dd", 5);
            for (int j = 0; j < longitud; j++) {
                parrafo.add("GEREDU CUSCO\n\n");
                for (int i = 0; i < 13; i++) {
                    parrafo.add(campos_boleta[i]+": "+boleta.get(n)+"\n");
                    n++;
                }
                parrafo.add("======================================================================\n");
                eliminar_null(campos_haberes,haberes,aux_campos_h_d,aux_valores_h_d,ini_h,fin_h);
                alinear_h_d(aux_campos_h_d);
                alinear_h_d_valores(aux_valores_h_d);
                for (int i = 0; i < aux_campos_h_d.size(); i++) {
                    parrafo.add("+"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i)+"\n");                  
                }
                aux_campos_h_d.clear();
                aux_valores_h_d.clear();            
                eliminar_null(campos_descuentos,descuentos,aux_campos_h_d,aux_valores_h_d,ini_d,fin_d);
                alinear_h_d(aux_campos_h_d);
                alinear_h_d_valores(aux_valores_h_d);
                for (int i = 0; i < aux_campos_h_d.size(); i++) {
                    parrafo.add("-"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i)+"\n");                 
                }
                aux_campos_h_d.clear();
                aux_valores_h_d.clear();
                parrafo.add("======================================================================\n");
                alinear_campos_importes(campos_importes);
                alinear_valores_importes(importes);
                parrafo.add(campos_importes.get(0)+"  "+importes.get(p)+"  "+campos_importes.get(1)+"  "+importes.get(p+1)+"  "+campos_importes.get(2)+"  "+importes.get(p+2)+"\n\n\n");
                String formattedString = String.format(formatString, j+1);
                parrafo.add("                                                                 "+formattedString+"\n");
                parrafo.add("....................................OTRO...............................\n\n");
                ini_h+=50;
                fin_h+=50;
                ini_d+=77;
                fin_d+=77;
                p+=3;
            } 
            doc.add(parrafo);
            doc.close();
            JOptionPane.showMessageDialog(null, "Se generó correctamente su archivo en pdf.\nUbicación: Documentos");
        } catch (FileNotFoundException | DocumentException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error, no se pudo generar su pdf: \n"+e);
        }            
    }        
      ///////////////////
  /*  public void generar_boleta_pdf(String []campos_boleta, ArrayList campos_importes, ArrayList campos_haberes, ArrayList campos_descuentos, 
            ArrayList<String> boleta,ArrayList<String> importes,ArrayList<String> haberes,ArrayList<String> descuentos){
        try {            
            String entorno = System.getenv("USERNAME");
            LocalDateTime d = LocalDateTime.now();
            String date = d.toString();
            String r = "";
            String [] xd = date.split(":");
            for (int i = 0; i < xd.length -1; i++) {
                r=r+xd[i]+"_";
            }
            String ruta = "C:\\Users\\"+entorno+"\\Documents\\"+r+"Archivo.pdf";
            Document doc = new Document();
            PdfWriter.getInstance(doc,new FileOutputStream(ruta));            
            doc.open();
            Paragraph parrafo = new Paragraph();
            parrafo.setFont(FontFactory.getFont("COURIER", 12));
            ArrayList<String> aux_campos_h_d = new ArrayList();
            ArrayList<String> aux_valores_h_d = new ArrayList();
            int n=0;
            int ini_h=0, fin_h=50;
            int ini_d=0, fin_d=77;  
            parrafo.add("GEREDU CUSCO\n\n");
            for (int i = 0; i < 13; i++) {
                parrafo.add(campos_boleta[i]+": "+boleta.get(n)+"\n");
                n++;
            }
            parrafo.add("======================================================================\n");
            eliminar_null(campos_haberes,haberes,aux_campos_h_d,aux_valores_h_d,ini_h,fin_h);
            alinear_h_d(aux_campos_h_d);
            alinear_h_d_valores(aux_valores_h_d);
            for (int i = 0; i < aux_campos_h_d.size(); i++) {
                parrafo.add("+"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i)+"\n");                 
            }
            aux_campos_h_d.clear();
            aux_valores_h_d.clear();
            eliminar_null(campos_descuentos,descuentos,aux_campos_h_d,aux_valores_h_d,ini_d,fin_d);
            alinear_h_d(aux_campos_h_d);
            alinear_h_d_valores(aux_valores_h_d);
            for (int i = 0; i < aux_campos_h_d.size(); i++) {
                parrafo.add("-"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i)+"\n");                
            }
            aux_campos_h_d.clear();
            aux_valores_h_d.clear();
            parrafo.add("======================================================================\n");
            alinear_campos_importes(campos_importes);
            alinear_valores_importes(importes);
            parrafo.add(campos_importes.get(0)+"  "+importes.get(0)+"  "+campos_importes.get(1)+"  "+importes.get(1)+"  "+campos_importes.get(2)+"  "+importes.get(2));
            doc.add(parrafo);
            doc.close();
            JOptionPane.showMessageDialog(null, "Se generó correctamente su pdf.\nUbicación: Documentos");
        } catch (FileNotFoundException | DocumentException e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error, no se pudo generar su pdf: \n"+e);
        }         
    }
       */
    private void btn_GENERAR_REPORTE_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GENERAR_REPORTE_ActionPerformed
        boolean flag = validar_campos();
        if(flag){
            String mes = combo_mes.getSelectedItem().toString();
            String año = txt_year.getText(); 
            String pat = txt_ap_paterno.getText().trim();
            String mat = txt_ap_materno.getText().trim();
            String name = txt_nombres.getText().trim();
            String arr[] = {mes,año,pat,mat,name};
            try {
                int contador = c.verificar_consulta(arr);
                if(contador > 0){
                    String campos [] = c.campo_nombre();
                    String campos_boleta[] = new String[13];
                    ArrayList<String> campos_haberes = new ArrayList();
                    ArrayList<String> campos_descuentos = new ArrayList();
                    ArrayList<String> campos_importes = new ArrayList();
                    int ind = 0;
                    while(ind<13){
                        campos_boleta[ind] = campos[ind];
                        ind++;
                    }
                    while(ind<16){
                        campos_importes.add(campos[ind]);
                        ind++;
                    }
                    ind++;
                    while(ind<67){
                        campos_haberes.add(campos[ind]);
                        ind++;
                    }
                    ind++;
                    while(ind<145){
                        campos_descuentos.add(campos[ind]);
                        ind++;
                    }
                    campos_boleta = len(campos_boleta);
                    ArrayList<String> boleta = new ArrayList();
                    ArrayList<String> importes = new ArrayList();
                    ArrayList<String> haberes = new ArrayList();
                    ArrayList<String> descuentos = new ArrayList();           
                    c.valores_de_la_consulta_individual(boleta,importes,haberes, descuentos, arr);
                    if(rbtn_txt.isSelected()){
                        //if(contador>1){
                        generar_boleta_txt(campos_boleta,campos_importes,campos_haberes,campos_descuentos,boleta,importes,haberes,descuentos);
                       // }
                       
                    }
                    else if(rbtn_pdf.isSelected()){
                        generar_boleta_pdf(campos_boleta,campos_importes,campos_haberes,campos_descuentos,boleta,importes,haberes,descuentos);                       
                    }
                }
                else
                    JOptionPane.showMessageDialog(null, "¡No existe registro con tales datos!", "MENSAJE", JOptionPane.WARNING_MESSAGE);
                      
            } catch (SQLException | HeadlessException e) {
                JOptionPane.showMessageDialog(null, "Algo salió mal..."+e);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Complete y/o seleccione todos los campos adecuadamente...", "MENSAJE", JOptionPane.WARNING_MESSAGE);
            
    }//GEN-LAST:event_btn_GENERAR_REPORTE_ActionPerformed
    public boolean validar_campos(){
        boolean flag = false;
        if(txt_year.getText().length() == 4 && txt_ap_paterno.getText().length() > 0 && txt_ap_materno.getText().length() > 0 && txt_nombres.getText().length() > 0 && (rbtn_txt.isSelected()|| rbtn_pdf.isSelected())){
            flag = true;
        }        
        return flag;
    }
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        c.desconectar();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_inicio_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio_ActionPerformed
        try {
            menu = new frm_menu();
            menu.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frm_consulta.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_btn_inicio_ActionPerformed

    private void btn_planillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_planillaActionPerformed
        planilla = new frm_planilla_v2();
        planilla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_planillaActionPerformed

    private void btn_consolidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consolidadoActionPerformed
        consolidado = new frm_consolidado();
        consolidado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_consolidadoActionPerformed

    private void txt_yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_yearKeyTyped
        char validar = evt.getKeyChar();
        if(!Character.isDigit(validar) || txt_year.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_txt_yearKeyTyped
    int xx,yy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frm_consulta().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frm_consulta.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GENERAR_REPORTE_;
    private javax.swing.JButton btn_consolidado;
    private javax.swing.JButton btn_inicio_;
    private javax.swing.JButton btn_planilla;
    public static javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combo_mes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtn_pdf;
    private javax.swing.JRadioButton rbtn_txt;
    private javax.swing.JTextField txt_ap_materno;
    private javax.swing.JTextField txt_ap_paterno;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
