/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package planillas_drec;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author aE
 */
public class frm_back_up extends javax.swing.JFrame {

    /**
     * Creates new form frm_back_up
     */
    frm_menu menu;
    frm_z z;
    public frm_back_up() {
        initComponents();
        btn_z_.setVisible(false);
        setLocationRelativeTo(null);
    }
    cConexion c = new cConexion();
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/cap.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btn_GENERAR_REPORTE_ = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_inicio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_z_ = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combo_condicion = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_mes = new javax.swing.JComboBox();
        txt_respaldo_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("_");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btn_GENERAR_REPORTE_.setBackground(new java.awt.Color(255, 102, 0));
        btn_GENERAR_REPORTE_.setText("GENERAR BACKUP");
        btn_GENERAR_REPORTE_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GENERAR_REPORTE_ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/house.png"))); // NOI18N
        btn_inicio.setText("INICIO                ");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("GERENCIA REGIONAL");

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DE EDUCACIÓN CUSCO");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jLabel9.setText("© GEREDU/CENTRO CÓMPUTO 2021");

        btn_z_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zombie.png"))); // NOI18N
        btn_z_.setText("don't press!       ");
        btn_z_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_z_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_z_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_inicio)
                .addGap(0, 0, 0)
                .addComponent(btn_z_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("BACKUP BOLETAS");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("X");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("CONDICIÓN :");

        combo_condicion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTIVO", "CESANTE" }));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("AÑO             :");

        txt_year.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_yearKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("MES             :");

        combo_mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SETIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));

        txt_respaldo_.setText("RESPALDO");
        txt_respaldo_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_respaldo_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_respaldo_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_GENERAR_REPORTE_, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_year)
                                    .addComponent(combo_condicion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combo_mes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_condicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(combo_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_GENERAR_REPORTE_, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_respaldo_, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked
    public boolean validar_campos(){
        boolean flag = false;
        if(txt_year.getText().length() == 4 ){
            flag = true;
        }        
        return flag;
    }
    String[] nro_mes={"01","02","03","04","05","06","07","08","09","10","11","12"};
    String meses[] = {"ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SETIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE"};
    public String get_nro_mes(String mes){
        String nro = "";
        for (int i = 0; i < 12; i++) {
            if(mes.equals(meses[i])){
                nro = nro_mes[i];
                i=12;
            }
        }
        return nro;
    }
    public String[] len(String a[]){
        for (int i = 0; i < a.length; i++) {
            a[i] = String.format("%-25s", a[i]);
        }
        return a;       
    }
    public void eliminar_null(ArrayList nombre_campos_hab_des, ArrayList valor_hab_des,
            ArrayList campos_aux, ArrayList valor_aux,int p_ini, int p_fin){
        int k=0;
        for (int i = p_ini; i < p_fin; i++) {
            if(valor_hab_des.get(i)!=(null)){
                campos_aux.add(nombre_campos_hab_des.get(k));
                valor_aux.add(valor_hab_des.get(i));                
            }
            k++;       
        } 
    }
    public void alinear_h_d(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%-15s", a.get(i)));
        }   
    }
    public void alinear_h_d_valores(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%8s", a.get(i)));
        }   
    }
    public void alinear_campos_importes(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%-10s", a.get(i)));
        }   
    }
    public void alinear_valores_importes(ArrayList a){
        for (int i = 0; i < a.size(); i++) {
            a.set(i, String.format("%10s", a.get(i)));
        }   
    }
    public boolean crear_consolidado_txt(String[] arr, String ruta, String carpeta){
        boolean flag = false;
        String campos [];
        try {
            campos = c.campo_nombre();
            String campos_boleta[] = new String[13];
            ArrayList<String> campos_haberes = new ArrayList();
            ArrayList<String> campos_descuentos = new ArrayList();
            ArrayList<String> campos_importes = new ArrayList();
            int ind = 0;
            while(ind<13){
                campos_boleta[ind] = campos[ind];
                ind++;
            }
            while(ind<16){
                campos_importes.add(campos[ind]);
                ind++;
            }
            ind++;
            while(ind<67){
                campos_haberes.add(campos[ind]);
                ind++;
            }
            ind++;
            while(ind < 145){
                campos_descuentos.add(campos[ind]);
                ind++;
            }
            campos_boleta = len(campos_boleta);
            ArrayList<String> boleta = new ArrayList();
            ArrayList<String> importes = new ArrayList();
            ArrayList<String> haberes = new ArrayList();
            ArrayList<String> descuentos = new ArrayList();           
            c.valores_de_la_consulta_grupal(boleta,importes,haberes, descuentos, arr);
            FileWriter fw1;
            try {
                fw1 = new FileWriter(ruta+"\\boletas"+carpeta+".txt");
                BufferedWriter bw1 = new BufferedWriter(fw1);
                ArrayList<String> aux_campos_h_d = new ArrayList();
                ArrayList<String> aux_valores_h_d = new ArrayList();
                int n=0;
                int ini_h=0, fin_h=50;
                int ini_d=0, fin_d=77;
                int longitud = boleta.size()/13;
                int p = 0;
                String formatString = String.format("%%0%dd", 5);
                for (int j = 0; j < longitud; j++) {
                    bw1.newLine();
                    bw1.write("GEREDU CUSCO");
                    bw1.newLine();
                    bw1.newLine();
                    for (int i = 0; i < 13; i++) {
                        bw1.write(campos_boleta[i]+": "+boleta.get(n));
                        bw1.newLine();
                        n++;
                    }     
                    bw1.write("======================================================================");
                    bw1.newLine();
                    eliminar_null(campos_haberes,haberes,aux_campos_h_d,aux_valores_h_d,ini_h,fin_h);
                    alinear_h_d(aux_campos_h_d);
                    alinear_h_d_valores(aux_valores_h_d);
                    for (int i = 0; i < aux_campos_h_d.size(); i++) {
                        bw1.write("+"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                        bw1.newLine();                  
                    }
                    aux_campos_h_d.clear();
                    aux_valores_h_d.clear();
                    eliminar_null(campos_descuentos,descuentos,aux_campos_h_d,aux_valores_h_d,ini_d,fin_d);
                    alinear_h_d(aux_campos_h_d);
                    alinear_h_d_valores(aux_valores_h_d);
                    for (int i = 0; i < aux_campos_h_d.size(); i++) {
                        bw1.write("-"+aux_campos_h_d.get(i)+" "+aux_valores_h_d.get(i));
                        bw1.newLine();                  
                    }
                    aux_campos_h_d.clear();
                    aux_valores_h_d.clear();
                    bw1.write("======================================================================");     
                    bw1.newLine();
                    alinear_campos_importes(campos_importes);
                    alinear_valores_importes(importes);
                    bw1.write(campos_importes.get(0)+"  "+importes.get(p)+"  "+campos_importes.get(1)+"  "+importes.get(p+1)+"  "+campos_importes.get(2)+"  "+importes.get(p+2));   
                    bw1.newLine();
                    bw1.newLine();
                    bw1.newLine();
                    String formattedString = String.format(formatString, j+1);
                    bw1.write("                                                                 "+formattedString);
                    bw1.newLine();
                    bw1.write(".");
                    bw1.newLine();
                    bw1.newLine();
                    ini_h+=50;
                    fin_h+=50;
                    ini_d+=77;
                    fin_d+=77;
                    p+=3;
                } 
                bw1.close();
                fw1.close();
                flag = true;
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
            }    
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
        }
        return flag;
    }
    private void btn_GENERAR_REPORTE_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GENERAR_REPORTE_ActionPerformed
        boolean b = verify_z();
        if(b){
            btn_z_.setVisible(true);
        }
        else{
            boolean flag = validar_campos();
            if(flag){
                String mes = combo_mes.getSelectedItem().toString();
                String year = txt_year.getText();
                String condicion = combo_condicion.getSelectedItem().toString();
                String[] arr = {mes, year, condicion};
                try {
                    int contador = c.verificar_consulta_grupal(arr);
                    if(contador > 0){
                        ArrayList<String> valores = new ArrayList();
                        c.consulta_back_up_lineal(valores,arr);
                        String entorno = System.getenv("USERNAME");
                        String carpeta = year + get_nro_mes(mes);
                        String ruta;
                        if(condicion.equals("ACTIVO"))
                            ruta = "C:\\Users\\"+entorno+"\\Documents\\backup\\activos\\"+carpeta;
                        else
                            ruta = "C:\\Users\\"+entorno+"\\Documents\\backup\\cesantes\\"+carpeta;
                        FileWriter fw1;
                        try {
                            File f = new File(ruta);
                            f.mkdirs();//crea varios directorios si no los hubiera
                            boolean bandera = crear_consolidado_txt(arr,ruta,carpeta);
                            if(bandera){
                                fw1 = new FileWriter(ruta+"\\ejecucion"+carpeta+".txt");
                                BufferedWriter bw1 = new BufferedWriter(fw1);
                                int len_consulta = valores.size() / 148;
                                int n = 0;
                                for (int j = 0; j < len_consulta; j++) {
                                    for (int i = 0; i < 147; i++) {
                                        bw1.write(valores.get(n)+";");
                                        n++;  
                                    }
                                    bw1.write(valores.get(n)+"");
                                    n++;
                                    bw1.newLine();
                                }
                                bw1.close();
                                fw1.close();
                                JOptionPane.showMessageDialog(null, "Se generó correctamente sus archivos de backup.\nUbicación: Documentos\\backup");
                            }   
                            else
                                JOptionPane.showMessageDialog(null, "Algo salió mal...\n No se generó su backup");
                        } catch (IOException ex) {
                            JOptionPane.showMessageDialog(null, "Algo salió mal...\n "+ex, "MENSAJE", JOptionPane.WARNING_MESSAGE);
                        } 
                    }
                    else
                        JOptionPane.showMessageDialog(null, "¡No existe registro alguno con tales datos!", "MENSAJE", JOptionPane.WARNING_MESSAGE);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Complete los campos adecuadamente...", "MENSAJE", JOptionPane.WARNING_MESSAGE);
        }      
    }//GEN-LAST:event_btn_GENERAR_REPORTE_ActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        try {
            menu = new frm_menu();
            menu.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
        }          
    }//GEN-LAST:event_btn_inicioActionPerformed
    int xx,yy;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        c.desconectar();
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txt_yearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_yearKeyTyped
        char validar = evt.getKeyChar();
        if(!Character.isDigit(validar) || txt_year.getText().length()>=4){
            evt.consume();
        }
    }//GEN-LAST:event_txt_yearKeyTyped
    public boolean verify_z(){
        boolean flag = false;
        if(txt_year.getText().equals("0004") && combo_mes.getSelectedItem().equals("JUNIO")){
            flag = true;
        }        
        return flag;
    }
    private void txt_respaldo_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_respaldo_ActionPerformed
            int desicion = JOptionPane.showConfirmDialog(null, "¿Seguro que desea generar un respaldo\nde los datos almacenados en las\n tablas boletas, haberes y descuentos?","Mensaje Consulta",JOptionPane.YES_NO_OPTION);
            if(desicion==JOptionPane.YES_OPTION){
                // aqui almaceno los valores de las consultas
                ArrayList<String> value_b = new ArrayList();
                ArrayList<String> value_h = new ArrayList();
                ArrayList<String> value_d = new ArrayList();         
                c.respaldo_tabla_b("tBoletas", value_b); 
                c.respaldo_tablas_h_d("tHaberes", value_h); 
                c.respaldo_tablas_h_d("tDescuentos", value_d); 
                String entorno = System.getenv("USERNAME");
                LocalDateTime d = LocalDateTime.now();
                String date = d.toString();
                String r = "";
                String [] xd = date.split(":");
                int z;
                for (z = 0; z < xd.length-1; z++) {
                    r=r+xd[z]+".";
                }
                r+=xd[z];
                String ruta = "C:\\Users\\"+entorno+"\\Documents\\respaldo_tabla_planillas\\"+r;
                try {
                    File f = new File(ruta);
                    f.mkdirs();
                    FileWriter fw1 = new FileWriter(ruta+"\\tabla3_boletas.txt");
                    BufferedWriter bw1 = new BufferedWriter(fw1);
                    FileWriter fw2 = new FileWriter(ruta+"\\tabla1_haberes.txt");
                    BufferedWriter bw2 = new BufferedWriter(fw2);
                    FileWriter fw3 = new FileWriter(ruta+"\\tabla2_descuentos.txt");
                    BufferedWriter bw3 = new BufferedWriter(fw3);
                    int len_b = value_b.size() / 19;//len boletas = 19 campos
                    int len_h = value_h.size() / 51;//len haberes = 51 campos
                    int len_d = value_d.size() / 78;//len descuentos = 78 campos            
                    int n = 0;
                    for (int j = 0; j < len_b; j++) {
                        for (int i = 0; i < 18; i++) {
                            bw1.write(value_b.get(n)+";");
                            n++;  
                        }
                        bw1.write(value_b.get(n)+"");
                        n++;
                        bw1.newLine();
                    }
                    n=0;
                    for (int j = 0; j < len_h; j++) {
                        for (int i = 0; i < 50; i++) {
                            bw2.write(value_h.get(n)+";");
                            n++;  
                        }
                        bw2.write(value_h.get(n)+"");
                        n++;
                        bw2.newLine();
                    }
                    n=0;
                    for (int j = 0; j < len_d; j++) {
                        for (int i = 0; i < 77; i++) {
                            bw3.write(value_d.get(n)+";");
                            n++;  
                        }
                        bw3.write(value_d.get(n)+"");
                        n++;
                        bw3.newLine();
                    }
                    bw1.close();
                    fw1.close();
                    bw2.close();
                    fw2.close();
                    bw3.close();
                    fw3.close();
                    JOptionPane.showMessageDialog(null, "Se generó correctamente su respaldo.\nUbicación: Documentos\\respaldo_tabla_planillas");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Algo salió mal...\n"+ex);
                }
            }      
    }//GEN-LAST:event_txt_respaldo_ActionPerformed

    private void btn_z_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_z_ActionPerformed
        z = new frm_z();
        z.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_z_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_back_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_back_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_back_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_back_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_back_up().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_GENERAR_REPORTE_;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_z_;
    private javax.swing.JComboBox combo_condicion;
    private javax.swing.JComboBox combo_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton txt_respaldo_;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
